# Copyright 2015 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""Description

Revision ID: 3a6b3db996b6
Revises: juno
Create Date: 2015-02-18 16:08:05.117122

"""

# revision identifiers, used by Alembic.
revision = '3a6b3db996b6'
down_revision = 'juno'

from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisco_phy_routers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('cisco_phy_router_port_bindings',
    sa.Column('port_id', sa.String(length=36), nullable=False),
    sa.Column('subnet_id', sa.String(length=36), nullable=True),
    sa.Column('router_id', sa.String(length=36), nullable=True),
    sa.Column('phy_router_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['phy_router_id'], ['cisco_phy_routers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('port_id'),
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cisco_phy_router_port_bindings')
    op.drop_table('cisco_phy_routers')
    ### end Alembic commands ###

if __name__ == "__main__":
    upgrade()
