service openstack-ceilometer-alarm-evaluator stop
service openstack-ceilometer-alarm-notifier stop
service openstack-ceilometer-api stop
service openstack-ceilometer-central stop
service openstack-ceilometer-collector stop
service openstack-ceilometer-notification stop
service openstack-cinder-api stop
service openstack-cinder-backup stop
service openstack-cinder-scheduler stop
service openstack-cinder-volume stop
service openstack-glance-api stop
service openstack-glance-registry stop
service openstack-heat-api stop
service openstack-heat-engine stop
service openstack-keystone stop
service openstack-nova-api stop
service openstack-nova-cert stop
service openstack-nova-conductor stop
service openstack-nova-consoleauth stop
service openstack-nova-novncproxy stop
service openstack-nova-scheduler stop
service openstack-swift-account-auditor stop
service openstack-swift-account-reaper stop
service openstack-swift-account-replicator stop
service openstack-swift-account stop
service openstack-swift-container-auditor stop
service openstack-swift-container-replicator stop
service openstack-swift-container-updater stop
service openstack-swift-container stop
service openstack-swift-object-auditor stop
service openstack-swift-object-replicator stop
service openstack-swift-object-updater stop
service openstack-swift-object stop
service openstack-swift-proxy stop
service neutron-cisco-cfg-agent stop
service neutron-dhcp-agent stop
service neutron-metadata-agent stop
service neutron-openvswitch-agent stop    
service neutron-server stop
