service openstack-ceilometer-alarm-evaluator restart
service openstack-ceilometer-alarm-notifier restart
service openstack-ceilometer-api restart
service openstack-ceilometer-central restart
service openstack-ceilometer-collector restart
service openstack-ceilometer-notification restart
service openstack-cinder-api restart
service openstack-cinder-backup restart
service openstack-cinder-scheduler restart
service openstack-cinder-volume restart
service openstack-glance-api restart
service openstack-glance-registry restart
service openstack-heat-api restart
service openstack-heat-engine restart
service openstack-keystone restart
service openstack-nova-api restart
service openstack-nova-cert restart
service openstack-nova-conductor restart
service openstack-nova-consoleauth restart
service openstack-nova-novncproxy restart
service openstack-nova-scheduler restart
service openstack-swift-account-auditor restart
service openstack-swift-account-reaper restart
service openstack-swift-account-replicator restart
service openstack-swift-account restart
service openstack-swift-container-auditor restart
service openstack-swift-container-replicator restart
service openstack-swift-container-updater restart
service openstack-swift-container restart
service openstack-swift-object-auditor restart
service openstack-swift-object-replicator restart
service openstack-swift-object-updater restart
service openstack-swift-object restart
service openstack-swift-proxy restart
service neutron-cisco-cfg-agent restart
service neutron-dhcp-agent restart
service neutron-metadata-agent restart
service neutron-openvswitch-agent restart
service neutron-server restart   
